//
//  MovieSearchRouter.swift
//  iOS_OTT
//
//  Created by 최민준 on 1/18/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieSearchRoutingLogic {
    func routeToMovieDetailPage(movieId: Int)
}

protocol MovieSearchDataPassing {
    var dataStore: MovieSearchDataStore? { get }
}

class MovieSearchRouter: NSObject, MovieSearchRoutingLogic, MovieSearchDataPassing {
    weak var viewController: MovieSearchViewController?
    var dataStore: MovieSearchDataStore?
    
    func routeToMovieDetailPage(movieId: Int) {
        let page = MovieDetailViewController()
        page.modalPresentationStyle = .fullScreen
        var dataStore = page.router?.dataStore
        dataStore?.movieId = movieId
    
        self.viewController?.present(page, animated: true)
    }
}
