//
//  MovieSearchInteractor.swift
//  iOS_OTT
//
//  Created by 최민준 on 1/18/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import Alamofire


protocol MovieSearchBusinessLogic {
    func requestPageInfo(request: MovieSearch.PageInfo.Request)
}

protocol MovieSearchDataStore {
    
}

class MovieSearchInteractor: MovieSearchBusinessLogic, MovieSearchDataStore {
    var presenter: MovieSearchPresentationLogic?
    
    private let disposeBag: DisposeBag = .init()
    
    private var nowPlayingListPageNum: Int = 1
    
    private let apiKey = "8dfb5cff049f9d201dd76dbbe04a0d71"
    private let language = "ko-RK" //en-US

    
    // MARK: Do something
    
    func requestPageInfo(request: MovieSearch.PageInfo.Request) {
        self.requestMovieList(listType: request.listType, pageNum: nowPlayingListPageNum).subscribe(onSuccess: { (list) in
            self.presenter?.presentPageInfo(response: .init(movieListData: list))
        }, onFailure: { (error) in
            self.presenter?.presentPageInfoError(response: .init(error: error))
        }).disposed(by: self.disposeBag)
    }
    
    // 영화 리스트 데이터 호출
    func requestMovieList(listType: MovieSearch.ListType, pageNum: Int) -> Single<MovieListDataModel> {
        Single.create { (observer) -> Disposable in
            let url = "https://api.themoviedb.org/3/movie/\(listType.rawValue)?api_key=\(self.apiKey)&language=\(self.language)&page=\(pageNum)"
            AF.request(url, method: .get)
                .validate(contentType: ["application/json"])
                .responseJSON { response in
                    print(response.result) //들어옴
                    switch response.result {
                    case .success(_):
                        print("API Connect Success - PopularList")
                        guard let result = response.data else { return }
                        do {
                            let dto = try JSONDecoder().decode(MovieListDataModel.self, from: result)
                            observer(.success(dto))
                        } catch (let error) {
                            observer(.failure(error))
                        }
                        
                    case .failure(let error):
                        print("API Connect Fail - PopularList")
                        observer(.failure(error))
                    }
                }
            return Disposables.create {}
        }
    }
}
