//
//  MovieSearchPresenter.swift
//  iOS_OTT
//
//  Created by 최민준 on 1/18/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


protocol MovieSearchPresentationLogic {
    func presentPageInfo(response: MovieSearch.PageInfo.Response)
}

class MovieSearchPresenter: MovieSearchPresentationLogic {
    weak var viewController: MovieSearchDisplayLogic?
    
    // MARK: Do something
    
    func presentPageInfo(response: MovieSearch.PageInfo.Response) {
        let viewModel = MovieSearch.PageInfo.ViewModel()
        viewController?.displayPageInfo(viewModel: viewModel)
    }
}
