//
//  MovieSearchModels.swift
//  iOS_OTT
//
//  Created by 최민준 on 1/18/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieSearch {
    // 영화 리스트 타입
    enum ListType: String {
        case nowPlaying = "now_playing"
        case popular = "popular"
        case topRated = "top_rated"
        case upComing = "upcoming"
    }
    
    enum PageInfo {
        struct Request {
            enum PageType {
                case first
                case next
            }
            
            var listType: ListType
            var pageType: PageType
        }
        struct Response {
            var movieListData: MovieListDataModel?
            var error: Error?
        }
        struct ViewModel {
            var listType: ListType?
            var cellModel: MovieSearchViewModel.MovieListDataModel?
            var error: Error?
        }
    }
}
