//
//  MovieSearchInteractor.swift
//  iOS_OTT
//
//  Created by 최민준 on 1/18/24.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


protocol MovieSearchBusinessLogic {
    func requestPageInfo(request: MovieSearch.PageInfo.Request)
}

protocol MovieSearchDataStore {
    
}

class MovieSearchInteractor: MovieSearchBusinessLogic, MovieSearchDataStore {
    var presenter: MovieSearchPresentationLogic?
    
    
    // MARK: Do something
    
    func requestPageInfo(request: MovieSearch.PageInfo.Request) {
        let response = MovieSearch.PageInfo.Response()
        self.presenter?.presentPageInfo(response: response)
    }
}
