//
//  OTTMainWorker.swift
//  iOS_OTT
//
//  Created by 최민준(Minjun Choi) on 2023/04/07.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import Alamofire


class OTTMainWorker {
    let apiKey = "8dfb5cff049f9d201dd76dbbe04a0d71"
    let language = "ko-RK" //en-US
    
    // 영화 리스트 데이터 호출 
    func requestMovieList(listType: OTTMain.ListType, pageNum: Int) -> Single<MovieListModel> {
        Single.create { (observer) -> Disposable in
            let url = "https://api.themoviedb.org/3/movie/\(listType.rawValue)?api_key=\(self.apiKey)&language=\(self.language)&page=\(pageNum)"
            AF.request(url, method: .get)
                .validate(contentType: ["application/json"])
                .responseJSON { response in
                    print(response.result) //들어옴
                    switch response.result {
                    case .success(_):
                        print("API Connect Success - PopularList")
                        guard let result = response.data else { return }
                        do {
                            let dto = try JSONDecoder().decode(MovieListModel.self, from: result)
                            observer(.success(dto))
                        } catch (let error) {
                            observer(.failure(error))
                        }
                        
                    case .failure(let error):
                        print("API Connect Fail - PopularList")
                        observer(.failure(error))
                    }
                }
            return Disposables.create {}
        }
    }
}
