//
//  OTTModels.swift
//  iOS_OTT
//
//  Created by 최민준(Minjun Choi) on 2023/04/07.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum OTT {

    enum MovieType {
        case popular
        case nowPlaying
        case topRated
        case upComing
    }
    
    // MARK: Use cases
        
    enum Something {
        struct Request {
            enum PageType {
                case first
                case next
            }
            
            var movieType: MovieType
            var pageType: PageType
        }
        struct Response {
            var movieType: MovieType?
            var popularMovieListData: PopularMovieListModel?
            var nowPlayingMovieListData: NowPlayingMovieListModel?
            var topRatedMovieListData: TopRatedMovieListModel?
            var upComingMovieListData: UpComingMovieListModel?
            var error: Error?
        }
        struct ViewModel{
            var movieType: MovieType?
            var cellModel: OTTViewModel.MovieListModel?
        }
    }
}
