//
//  OTTMainRouter.swift
//  iOS_OTT
//
//  Created by 최민준(Minjun Choi) on 2023/04/07.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OTTMainRoutingLogic {
}

protocol OTTMainDataPassing {
    var dataStore: OTTMainDataStore? { get }
}

class OTTMainRouter: NSObject, OTTMainRoutingLogic, OTTMainDataPassing {
    weak var viewController: OTTMainViewController?
    var dataStore: OTTMainDataStore?

}
