//
//  OTTMainRouter.swift
//  iOS_OTT
//
//  Created by 최민준(Minjun Choi) on 2023/04/07.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OTTMainRoutingLogic {
    func routeToMovieDetailPage(listType: OTTMain.ListType, index: Int)
}

protocol OTTMainDataPassing {
    var dataStore: OTTMainDataStore? { get }
}

class OTTMainRouter: NSObject, OTTMainRoutingLogic, OTTMainDataPassing {
    weak var viewController: OTTMainViewController?
    var dataStore: OTTMainDataStore?

    func routeToMovieDetailPage(listType: OTTMain.ListType, index: Int) {
        let movieId = {
            switch listType {
            case .nowPlaying:
                return self.dataStore?.nowPlayingMovieList[index].id
            
            case .popular:
                return self.dataStore?.popularMovieList[index].id
                
            case .topRated:
                return self.dataStore?.nowPlayingMovieList[index].id
                
            case .upComing:
                return self.dataStore?.nowPlayingMovieList[index].id
            }
        }()
     
        let page = MovieDetailViewController()
        var dataStore = page.router?.dataStore
        dataStore?.movieId = movieId
        
        self.viewController?.present(page, animated: true)
//        self.viewController?.pushViewController(page, animated: true)
    }
}
