//
//  OTTRouter.swift
//  iOS_OTT
//
//  Created by 최민준(Minjun Choi) on 2023/04/07.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol OTTRoutingLogic {
}

protocol OTTDataPassing {
    var dataStore: OTTDataStore? { get }
}

class OTTRouter: NSObject, OTTRoutingLogic, OTTDataPassing {
    weak var viewController: OTTViewController?
    var dataStore: OTTDataStore?

}
