//
//  OTTWorker.swift
//  iOS_OTT
//
//  Created by 최민준(Minjun Choi) on 2023/04/07.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import RxSwift
import Alamofire


class OTTWorker {
    let apiKey = "1c07ffe0d8a785d0d1ed3d288170b276"
    let language = "ko-RK" //en-US
    
    func requestPopularMovieList(pageNum: Int) -> Single<PopularMovieListModel> {
        .create { (observer) in
            
            let url = "https://api.themoviedb.org/3/movie/popular?api_key=\(self.apiKey)&language=\(self.language)&page=\(pageNum)"
            AF.request(url, method: .get)
                .validate(contentType: ["application/json"])
                .responseJSON { response in
                    print(response.result) //들어옴
                    switch response.result {
                    case .success(_):
                        print("API Connect Success - PopularList")
                        guard let result = response.data else { return }
                        do {
                            let dto = try JSONDecoder().decode(PopularMovieListModel.self, from: result)
                            observer(.success(dto))
                        } catch (let error) {
                            observer(.failure(error))
                        }
                        
                    case .failure(let error):
                        print("API Connect Fail - PopularList")
                        observer(.failure(error))
                    }
                }
            return Disposables.create {}
        }
    }
    
    func requestNowPlayingMovieList(pageNum: Int) -> Single<NowPlayingMovieListModel> {
        .create { (observer) in
            
            let url = "https://api.themoviedb.org/3/movie/now_playing?api_key=\(self.apiKey)&language=\(self.language)&page=\(pageNum)"
            AF.request(url, method: .get)
                .validate(contentType: ["application/json"])
                .responseJSON { response in
                    print(response.result) //들어옴
                    switch response.result {
                    case .success(_):
                        print("API Connect Success - PopularList")
                        guard let result = response.data else { return }
                        do {
                            let dto = try JSONDecoder().decode(NowPlayingMovieListModel.self, from: result)
                            observer(.success(dto))
                        } catch (let error) {
                            observer(.failure(error))
                        }
                        
                    case .failure(let error):
                        print("API Connect Fail - PopularList")
                        observer(.failure(error))
                    }
                }
            return Disposables.create {}
        }
    }
    
    func requestTopRatedMovieList(pageNum: Int) -> Single<TopRatedMovieListModel> {
        .create { (observer) in
            
            let url = "https://api.themoviedb.org/3/movie/top_rated?api_key=\(self.apiKey)&language=\(self.language)&page=\(pageNum)"
            AF.request(url, method: .get)
                .validate(contentType: ["application/json"])
                .responseJSON { response in
                    print(response.result) //들어옴
                    switch response.result {
                    case .success(_):
                        print("API Connect Success - PopularList")
                        guard let result = response.data else { return }
                        do {
                            let dto = try JSONDecoder().decode(TopRatedMovieListModel.self, from: result)
                            observer(.success(dto))
                        } catch (let error) {
                            observer(.failure(error))
                        }
                        
                    case .failure(let error):
                        print("API Connect Fail - PopularList")
                        observer(.failure(error))
                    }
                }
            return Disposables.create {}
        }
    }

    func requestUpComingMovieList(pageNum: Int) -> Single<UpComingMovieListModel> {
        .create { (observer) in
            
            let url = "https://api.themoviedb.org/3/movie/upcoming?api_key=\(self.apiKey)&language=\(self.language)&page=\(pageNum)"
            AF.request(url, method: .get)
                .validate(contentType: ["application/json"])
                .responseJSON { response in
                    print(response.result) //들어옴
                    switch response.result {
                    case .success(_):
                        print("API Connect Success - PopularList")
                        guard let result = response.data else { return }
                        do {
                            let dto = try JSONDecoder().decode(UpComingMovieListModel.self, from: result)
                            observer(.success(dto))
                        } catch (let error) {
                            observer(.failure(error))
                        }
                        
                    case .failure(let error):
                        print("API Connect Fail - PopularList")
                        observer(.failure(error))
                    }
                }
            return Disposables.create {}
        }
    }
}
