//
//  OTTMainModels.swift
//  iOS_OTT
//
//  Created by 최민준(Minjun Choi) on 2023/04/07.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum OTTMain {
    
    // 영화 리스트 타입
    enum ListType: String {
        case nowPlaying = "now_playing"
        case popular = "popular"
        case topRated = "top_rated"
        case upComing = "upcoming"
    }
    
    // MARK: Use cases
        
    enum Something {
        struct Request {
            enum PageType {
                case first
                case next
            }
            
            var listType: ListType
            var pageType: PageType
        }
        struct Response {
            var listType: ListType?
            var nowPlayingMovieListData: MovieListDataModel?
            var popularMovieListData: MovieListDataModel?
            var topRatedMovieListData: MovieListDataModel?
            var upComingMovieListData: MovieListDataModel?
            var error: Error?
        }
        struct ViewModel{
            var listType: ListType?
            var cellModel: OTTMainViewModel.MovieListDataModel?
        }
    }
}
