//
//  MovieDetailPresenter.swift
//  iOS_OTT
//
//  Created by 최민준 on 12/11/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MovieDetailPresentationLogic {
    func presentPageInfo(response: MovieDetail.Something.Response)
    func presentPageInfoError(response: MovieDetail.Something.Response)
}

class MovieDetailPresenter: MovieDetailPresentationLogic {
    weak var viewController: MovieDetailDisplayLogic?
    
    // MARK: Do something
    
    func presentPageInfo(response: MovieDetail.Something.Response) {
        let viewModel = MovieDetail.Something.ViewModel()
        self.viewController?.displayPageInfo(viewModel: viewModel)
    }
    
    func presentPageInfoError(response: MovieDetail.Something.Response) {
        
    }
}
