//
//  MovieDetailModels.swift
//  iOS_OTT
//
//  Created by 최민준 on 12/11/23.
//  Copyright (c) 2023 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MovieDetail {
    // MARK: Use cases
    
    enum Something {
        struct Request {
        }
        struct Response {
            var movieDetailData: MovieDetailDataModel? 
            var error: Error?
        }
        struct ViewModel {
            var viewModel: MovieDetailViewModel?
            var error: Error? 
        }
    }
}
